---
- name: upgrade all packages
  yum: name=* state=latest
  sudo: yes

- name: clear cache
  command: yum clean all
  sudo: yes

- name: install remi-repo
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=present
  sudo: yes

- name: install epel-repo
  yum: name=epel-release state=present
  sudo: yes

- name: install utils
  yum: name={{ item }} state=present
  with_items:
    - which
    - sudo
    - wget
    - curl
    - make
    - gcc
    - git
    - openssl-devel # ruby build
    - sqlite-devel # ruby on rails build
  sudo: yes

- name: configure git
  command: git config --global {{ item }}
  with_items:
    - color.ui auto
    - core.editor "vim"

- name: install vim
  yum: name=vim state=present
  sudo: yes

- name: install neobundle 
  git: repo=https://github.com/Shougo/neobundle.vim dest={{ home }}/.vim/bundle/neobundle.vim

- name: install zsh
  yum: name=zsh state=present
  sudo: yes

- name: change default shell to zsh
  user: name={{ user }} shell=/bin/zsh
  sudo: yes

- name: install prezto (1)
  git: repo=https://github.com/sorin-ionescu/prezto.git dest={{ home }}/.zprezto recursive=yes

- name: install prezto (2)
  file: src={{ item }} dest={{ home }}/.{{ item | basename }} state=link
  with_fileglob:
    - "{{ home }}/.zprezto/runcoms/z*"

- name: install anyenv
  git: repo=https://github.com/riywo/anyenv dest={{ home }}/.anyenv

- name: install dotfiles (1)
  git: repo=https://github.com/castaneai/dotfiles dest={{ home }}/.dotfiles

- name: install dotfiles (2)
  file: src={{ item }} dest={{ home }}/{{ item | basename }} state=link
  with_fileglob:
    - "{{ home }}/.dotfiles/.*"
