---
- name: install nginx
  yum:
    name: nginx
    state: present 

- name: create nginx group
  group:
    name: "{{ nginx_group }}"
    state: present

- name: create nginx user
  user:
    name: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    home: "{{ nginx_www_dir }}"
    system: yes
    state: present

- name: create document root directory 
  file:
    path: "{{ nginx_www_dir }}"
    owner: web 
    group: web  
    mode: 0775
    state: directory

- name: create nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: create default server directory
  file:
    path: "{{ nginx_www_dir }}/default"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0775
    state: directory

- name: create default server config
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify:
    - restart nginx

- name: enable nginx service
  service:
    name: nginx
    state: started
    enabled: yes
