---
- name: Install nginx
  yum:
    name: nginx
    state: present 
  sudo: yes

- name: Create document root directory
  file:
    path: "{{ nginx_www_dir }}"
    mode: 0775
    owner: nginx
    group: nginx
    state: directory
  sudo: yes

- name: Create nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx
  sudo: yes

- name: Create default server directory
  file:
    path: "{{ nginx_www_dir }}/default"
    mode: 0775
    owner: nginx
    group: nginx
    state: directory
  sudo: yes

- name: Create default server config
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify:
    - restart nginx
  sudo: yes

- name: Enable nginx service
  service:
    name: nginx
    state: started
    enabled: yes
  sudo: yes
