---
- name: Install epel repo
  yum:
    name: epel-release
    state: present
  sudo: yes

- name: Install mysql client & server
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: remi
  with_items:
    - mariadb
    - mariadb-server
    - MySQL-python
  sudo: yes

- name: Enable mysql service
  service:
    name: mariadb
    state: started
    enabled: yes
  sudo: yes

- name: Check .my.cnf file already exists
  stat:
    path: "{{ lookup('env', 'HOME') }}/.my.cnf"
  register: mycnf_file

- name: Configure mysql root account
  mysql_user:
    name: "root"
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
  with_items:
    - 127.0.0.1
    - ::1    
    - localhost
  when: mycnf_file.stat.exists == false

- name: Copy .my.cnf file
  template:
    src: my.cnf.j2
    dest: "{{ lookup('env', 'HOME') }}/.my.cnf"
    mode: 0600

- name: Remove anonymous mysql user
  mysql_user:
    name: ""
    state: absent

- name: Create database
  mysql_db:
    name: "{{ mysql_db_name }}"
    state: present
  when: mysql_db_name is defined

- name: Create mysql user
  mysql_user:
    name: "{{ mysql_db_user }}"
    password: "{{ mysql_db_password }}"
    priv: "{{ mysql_db_name }}.*:ALL"
    host: "localhost"
    state: present
  when:
    - mysql_db_name is defined
    - mysql_db_user is defined
    - mysql_db_password is defined
