---
- name: Download wordpress
  get_url:
    url: "{{ wp_download_url }}"
    dest: "/tmp/wordpress.tar.gz"

- name: Extract wordpress archive
  unarchive:
    src: "/tmp/wordpress.tar.gz"
    dest: "{{ wp_dir }}"
  sudo: yes

- name: Fetch random salt
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"

- name: Configure wordpress
  template:
    src: wp-config.php.j2
    dest: "{{ wp_dir }}/wp-config.php"
  sudo: yes

- name: Change ownership wordpress directory
  file:
    path: "{{ wp_dir }}"
    owner: nginx
    group: nginx
    state: directory
    recurse: yes
  sudo: yes

- name: Configure nginx
  template:
    src: nginx-wordpress.conf.j2
    dest: /etc/nginx/conf.d/wordpress.conf
  notify: reload nginx
  sudo: yes

